

name: Issue and PR Actions

on:
  issues:
    types: [closed]
  pull_request:
    types: [opened]

jobs:
  issue-closed:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue closure
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload;
            const issue = payload.issue;
            const owner = payload.repository.owner.login;
            const repo = payload.repository.name;
            const commentBody = 'The issue is now resolved.';
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            await octokit.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue.number,
              body: commentBody
            });

  pr-opened:
    runs-on: ubuntu-latest
    steps:
      - name: Congratulate on first PR
        if: github.event.pull_request.commits == 1
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload;
            const pullRequest = payload.pull_request;
            const owner = payload.repository.owner.login;
            const repo = payload.repository.name;
            const congratulatoryMessage = `Congratulations on opening your first pull request, @${pullRequest.user.login}!`;
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            await octokit.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: pullRequest.number,
              body: congratulatoryMessage
            });
